CREATE DATABASE dbflashpomo;

USE dbflashpomo;

CREATE TABLE USER (
    USER_ID INT PRIMARY KEY,
    NAME VARCHAR(200),
    PASSWORD VARCHAR(90),
    EMAIL VARCHAR(150) UNIQUE,
    RULE VARCHAR(10),
    AVATAR BLOB,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    STATUS VARCHAR(10)
);

CREATE TABLE ENSEMBLE (
    ENSEMBLE_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    DESCRIPTION TEXT,
    COVER BLOB
);

CREATE TABLE FLASHCARD (
    FLASHCARD_ID INT PRIMARY KEY,
    TITLE VARCHAR(150),
    CONTENT TEXT,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    ENSEMBLE_ID INT,
    FOREIGN KEY (ENSEMBLE_ID) REFERENCES ENSEMBLE(ENSEMBLE_ID)
);

CREATE TABLE FAVORITE (
    FAVORITE_ID INT PRIMARY KEY,
    FAVORITATION_DATE_TIMESTAMP TIMESTAMP,
    STATUS BOOLEAN,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE FAVORITE_FLASHCARD (
    FAVORITE_ID INT,
    FLASHCARD_ID INT,
    PRIMARY KEY (FAVORITE_ID, FLASHCARD_ID),
    FOREIGN KEY (FLASHCARD_ID) REFERENCES FLASHCARD(FLASHCARD_ID),
    FOREIGN KEY (FAVORITE_ID) REFERENCES FAVORITE(FAVORITE_ID)
);

CREATE TABLE FLASHCARD_USAGE_HISTORY (
    USAGE_HISTORY_ID INT PRIMARY KEY,
    ACCESS_DATE TIMESTAMP,
    FLASHCARD_ID INT,
    USER_ID INT,
    FOREIGN KEY (FLASHCARD_ID) REFERENCES FLASHCARD(FLASHCARD_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE FLASHCARD_HISTORY_ITEMS (
    USAGE_HISTORY_ID INT,
    FLASHCARD_ID INT,
    PRIMARY KEY (USAGE_HISTORY_ID, FLASHCARD_ID),
    FOREIGN KEY (USAGE_HISTORY_ID) REFERENCES FLASHCARD_USAGE_HISTORY(USAGE_HISTORY_ID),
    FOREIGN KEY (FLASHCARD_ID) REFERENCES FLASHCARD(FLASHCARD_ID)
);

CREATE TABLE BOX (
    BOX_ID INT PRIMARY KEY,
    PRICE INT,
    TITLE VARCHAR(120),
    COVER BLOB,
    DESCRIPTION TEXT,
    STATUS BOOLEAN,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE BOX_FLASHCARD (
    BOX_ID INT,
    FLASHCARD_ID INT,
    PRIMARY KEY (BOX_ID, FLASHCARD_ID),
    FOREIGN KEY (BOX_ID) REFERENCES BOX(BOX_ID),
    FOREIGN KEY (FLASHCARD_ID) REFERENCES FLASHCARD(FLASHCARD_ID)
);

CREATE TABLE PURCHASE (
    EMAIL VARCHAR(150) UNIQUE,
    RULE VARCHAR(10),
    AVATAR BLOB,
    PURCHASE_ID INT PRIMARY KEY,
    PURCHASE_DATE TIMESTAMP,
    STATUS VARCHAR(20),
    AMOUNT INT,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE PURCHASE_BOX (
    PURCHASE_ID INT,
    BOX_ID INT,
    PRIMARY KEY (PURCHASE_ID, BOX_ID),
    FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE(PURCHASE_ID),
    FOREIGN KEY (BOX_ID) REFERENCES BOX(BOX_ID)
);

CREATE TABLE POMODORO_STORY (
    POMODORO_STORY_ID INT PRIMARY KEY,
    START_DATE_TIMESTAMP TIMESTAMP,
    END_DATE_TIMESTAMP TIMESTAMP,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE LOGIN_SESSION (
    SESSION_ID INT PRIMARY KEY,
    DEVICE VARCHAR(100),
    LOGIN_DATE_TIMESTAMP TIMESTAMP,
    LOGOUT_DATE_TIMESTAMP TIMESTAMP,
    IP_ADDRESS VARCHAR(255),
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

